@baseUrl = http://localhost:54619

### GET v2 tickets
GET {{baseUrl}}/api/v2/tickets
Accept: application/json

### POST v2 ticket
POST {{baseUrl}}/api/v2/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Lab 10 ticket",
  "status": "New"
}

### DELETE v2 ticket
DELETE {{baseUrl}}/api/v2/tickets/1
Accept: application/json

### GET v1 tickets
GET {{baseUrl}}/api/tickets
Accept: application/json

### POST v1 ticket
POST {{baseUrl}}/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "Concert",
  "status": "New"
}

### PATCH v1 ticket status
PATCH {{baseUrl}}/api/tickets/1/status
Content-Type: application/json
Accept: application/json

{
  "status": "Closed"
}
